### ISSUE TITLE
As a writer, I want to be able to edit or delete a post after publishing it

### ISSUE THREAD

**Issue by gponsu** [happta/dapp#6]
If I make a mistake, I would like to be able to fix it, even though the article was already published.

If it is not possible, perhaps it would be necessary to inform the writer before publishing that he will not be able to edit.

**Comment by MiguelBel** [comment]
Hey Vicente, thanks for your suggestion. Is something it was a feature which was completely needed in order to run production publishing platforms.

You can see implemented the feature along this commits:

https://github.com/happta/dapp/commit/86d77c590cbaa31972c766fb11765868da497ece
https://github.com/happta/dapp/commit/4d8b86124b01bd03269b29d91cdae5ea3c58759b
https://github.com/happta/dapp/commit/e9f70adb9bdbe767b20513af4c23a815dbe76b0f

You can use it by having the writer mode activated while viewing a single content.

Thanks!

**Comment by gponsu** [comment]
Wow awesome! :clap: :clap: :clap: 

Thank you very much!
